### ISSUE TITLE
Нацепить лоадер

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#101]
У нас в верстке есть лоадер, т.е. хрень, которая отображается на экране при загрузке окна (попапа), можем ее нацепить?

Очень хочется эту штуку увидеть, так как сейчас можно нажать на ссылку попапа и пару сек просто ничего не происходит, пока окно не подгрузится с даными из базы данных. Немного напрягает.

![2016-02-22_80](https://cloud.githubusercontent.com/assets/9402056/13220290/2eb0357a-d997-11e5-8f9e-943a11b81af4.jpg)

**Comment by ArseniyDyupin** [comment]
это короче лютый гемор, мне кажется он пока не нужен, давай реализуем его потом, а пока отложим

**Comment by Saimonrac1** [comment]
ок, давай тогда на сл. релиз если будет актуально.
