### ISSUE TITLE
Клиенты: слетает верстка если больше 22 клиентов

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#102]
Надо сделать чтобы на страницу помещалось до 50 клиентов, снизу должны быть переходы на следующие страницы.

![2016-02-23_2](https://cloud.githubusercontent.com/assets/9402056/13248788/32e8424e-da42-11e5-803c-83a0da6a37fc.jpg)

**Comment by Saimonrac1** [comment]
Тоже самое нужно сделать на страницах Действия и Сделки. Если возможно, то надо сделать так, чтобы пагинация появлялась только тогда, когда у нас добавлен 50 клиент, действие или сделка на страницу.

**Comment by Saimonrac1** [comment]
типо такой хрени, можешь просто вывести такие значения а я потом сам по верстке их заточу

![2016-02-24_82](https://cloud.githubusercontent.com/assets/9402056/13291539/f3844550-db39-11e5-9d68-8eb5bef6275b.jpg)

**Comment by Saimonrac1** [comment]
Такая же штука отображается. Ничего не изменилось. База данных старая, файлы новые.

![2016-03-02_7](https://cloud.githubusercontent.com/assets/9402056/13461377/c8f0ebb8-e0a2-11e5-9aac-d216941002e3.jpg)

**Comment by ArseniyDyupin** [comment]
дк добавь больше 50 клиентов, отобразится пагинация, сейчас у тебя 26 отображается, могу сделать так, что бы пагинация отображалась на 25ти клинтах

**Comment by ArseniyDyupin** [comment]
у меня все норм, больше 50 клиентов и все ок с пагинацией, тут просто верстка кривовата

**Comment by ArseniyDyupin** [comment]
короче подойди ко мне, как на работу придешь
