### ISSUE TITLE
Дубли клиентов, действий, сделок и настроек

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#103]
Заходим в окно Новый клиент, вводим данные и несколько раз нажимаем на кнопку "Добавить" - нажму кнопку 5 раз и создастся 5 клиентов. Тоже самое происходит когда создаешь новые действия, новые сделки или настройки. Создаются дубли. С пользователями другая история, там нажмешь несколько раз, страница прогрузит и потом просто выдаст пустое окно.

Можно сделать так, чтобы такого не происходило? Типо если нажмешь несколько раз кнопку "Добавить", а создастся только один экземпляр. Эта задача не критична, но если не геморойно давай сделаем.

![2016-03-04_1](https://cloud.githubusercontent.com/assets/9402056/13518863/3231c6cc-e1f4-11e5-9ad6-1b80791caed3.jpg)
![2016-03-04_2](https://cloud.githubusercontent.com/assets/9402056/13518864/3243de3e-e1f4-11e5-8097-1ccc0f4bc6b2.jpg)
![2016-03-04_3](https://cloud.githubusercontent.com/assets/9402056/13518865/32497b00-e1f4-11e5-8d5f-902e73ca6cc0.jpg)

**Comment by ArseniyDyupin** [comment]
поставить блок на кнопку как в кабинете?

**Comment by Saimonrac1** [comment]
поставим блок на кнопку
