### ISSUE TITLE
Отчеты

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#104]
Добавляем 3 типа отчетов: Сводный отчет, Отчет по действиям, Отчет по сделкам.
Не стал их сильно усложнять (по формулам, %, и т.д.), но и с этими дел хватит.

Отчеты смогут просматривать все пользователи, конечно, каждый сможет увидеть отчет только по своим данным. В блоке "Формирование отчета" пользователь выбирает данные, которые хочет сформировать, нажимает "Показать" и в таблицу подставляются данные.

Ссылка на отчеты будет находиться в блоке где "Мой аккаунт". Пункт будет называться "Мои отчеты".

Доступы:
**Создатель компании** - видит всех и вся. 
**Руководитель** - может формировать отчет только по себе и по своим менеджерам. Во всех отчетах, в селекторе "Отчет по:" нет параметров "Руководители + связи", "Руководители без связей", "Все пользователи". Есть параметр "Я ответственный" - данные без связей с менеджерами, а также параметр "Менеджеры" - данные только его менеджеров.
**Менеджер** - формирует отчет только по себе. В отчете "Сводный отчет" в селекторе "Отчет по:" нет параметров "Руководители + связи", "Руководители без связей", "Все пользователи". В отчетах 
"Отчет по действиям" и "Отчет по сделкам" вообще не будет параметра "Отчет по:".

Пожелания: 
а) если возможно, то если в отчете будет отображаться одна строка данных, то убирать строку "Итого по всем:". Допустим, у нас менеджер смотрит "Отчет по действиям" и у него отобразится одна строка с его ФИО и данными по его действиям, а в строке "Итого по всем:" получается будет повтор этих данных. Будет выглядеть не красиво.
б) сделать для разных типов пользователей разные справки, имеется ввиду только справки где отчеты. Это нужно для того, чтобы не выводить для менеджеров и руководителей справку по функционалу, которого у них нет.

=====================================================

Скачать отчеты - https://yadi.sk/d/PYrOY5EmpxVwD
CSS для колонок я сам залью в проект, чтобы у тебя уже все готово было, когда ты начнешь.

**Comment by ArseniyDyupin** [comment]
Саша, мы же не договаривались на 1 отчет, а тут прямо мясо, тут работы вообще не мало

**Comment by ArseniyDyupin** [comment]
Саша, мы же договаривались на 1 отчет, а тут прямо мясо, тут работы вообще не мало

**Comment by ArseniyDyupin** [comment]
+ мне работа фильтров некоторых не понятна

**Comment by ArseniyDyupin** [comment]
в общем будет время, подойди, нужно уточнить моменты некоторые

**Comment by ArseniyDyupin** [comment]
Давай поступим так, добавим к сумме еще 4 тысячи (35 итого) и я запилю все отчеты с выпадающими фильтрами по датам

**Comment by Saimonrac1** [comment]
Да, давай так и сделаем.

**Comment by Saimonrac1** [comment]
По времени уточню: основной функционал готов, с отчетами делай как удобно. Если получится то  в течении 2 недель.
