### ISSUE TITLE
Клиенты: не правильно работает поиск по источникам

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#28]
Клиент  Игорь Николаевич имеет источник "SEO", произвожу поиск по источнику "Нет источника" и этот клиент отображается в списке. Так не должно быть - в списке должны отобразиться только клиенты с заданным параметром.

![2015-12-26_24](https://cloud.githubusercontent.com/assets/9402056/12006163/9694e524-abec-11e5-9b39-901dc039181c.jpg)

**Comment by Saimonrac1** [comment]
Наблюдается следующая штука: 
создаем нового клиента, в анкете хоть и видим что у него обозначено Нет источника, на самом деле это не так. Когда производим поиск на странице Клиенты по параметру Нет источника, то мы не сможем найти этого клиента. Мы сможем его найти только если зайдем в анкету клиента, в инфо о клиенте просто щелкнем по Нет источника, сохраним. Тогда сможем найти клиента в поиске по Нет источника.

**Comment by ArseniyDyupin** [comment]
эту ошибку исправлять не надо, такого произойти просто не сможет сейчас, сейчас нельзя будет создать клиента так что бы у него поле источник было пустое, сейчас туда по умолчанию прокидывается нет источника, ну вообще эта проблема только с твоими старыми клентами с новыми проблем не будет, если не понятно объяснил, могу в устной форме рассказать))

**Comment by Saimonrac1** [comment]
ок, тут првоерю

**Comment by Saimonrac1** [comment]
http://test.inclient.ru/page/clients_page
test2@inclient.ru
fdcede84

Зайди сам посмотри, файлы новые все и база с нуля. Создал нескольких пользователей, ищу в поиске по Нет источника - нету их! У этих клиентов вообще ничего не делал. Пользователя этого не трогаю, посмотри сам. Мистика какая то

![2016-02-18_53](https://cloud.githubusercontent.com/assets/9402056/13150508/e12a2660-d687-11e5-8244-032d19471cf2.jpg)
![2016-02-18_54](https://cloud.githubusercontent.com/assets/9402056/13150507/e12a2b92-d687-11e5-9040-b8f90ad5afa8.jpg)

**Comment by ArseniyDyupin** [comment]
ваще полная хрень у меня на локалке все работает, а дай мне доступ к базе

**Comment by ArseniyDyupin** [comment]
ошибку исправил, но что бы перепроверить надо создать нового клиента со старыми не покатит
