### ISSUE TITLE
Ошибка при восстановлении пароля + изменить текст письма

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#33]
Попробовал восстановить пароль от saimonrac@yandex.ru, вышла какая то какашка. Письмо с восстановлением пароля пришло, перешел по ссылке вышла другая уже цветная какашка PHP.

Также надо поменять текст письма с восстановлением пароль на этот:

Приветствуем, Александр Шворак (тут имя ставим)!

Вы запросили восстановление Вашего пароля на сайте inclient.ru.

Чтобы поменять пароль на другой, пройдите по этой ссылке (тут ставим ссылку)

или просто нажмите здесь

http://inclient:81/page/activation/key/9bb6778edd5f9595279eccbc

С уважением,
Администрация INCLIENT.RU
_____

Если у вас возникнут вопросы напишите в поддержку
support@inclient.ru

![2015-12-26_33](https://cloud.githubusercontent.com/assets/9402056/12006310/1d0c46aa-abf3-11e5-9b62-5e11c3631563.jpg)
![2015-12-26_34](https://cloud.githubusercontent.com/assets/9402056/12006311/1d0de1d6-abf3-11e5-9cef-2e77f65a2974.jpg)

**Comment by ArseniyDyupin** [comment]
починил, но мне нужна верстка страницы с успехом, посмотри как я сделал и все поймешь
