### ISSUE TITLE
Сделать валидацию всех форм

### ISSUE THREAD

**Issue by ArseniyDyupin** [ArseniyDyupin/SimpleCRM2#41]
Сделать валидацию всех форм

**Comment by ArseniyDyupin** [comment]
все оставшиеся задачи связаны с валидацией, точнее с ее отсутствием

**Comment by ArseniyDyupin** [comment]
думаю за неделю должен ее запилить, а может и раньше, если быстро разберусь как ее сделать

**Comment by ArseniyDyupin** [comment]
Осталось сделать валидацию редактируемых записей, пока ума не приложу как ее прикрутить

**Comment by saimonrac** [comment]
если будет какое простое решение, то можно его прикрутить пока

**Comment by ArseniyDyupin** [comment]
все сделал, я норм чувак

**Comment by Saimonrac1** [comment]
молорик!
