### ISSUE TITLE
Подтверждение регистрации: ссылка не в том месте

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#42]
В письме активации, активная ссылка стоит на слове "ссылке", нужно сделать активную ссылку на слове "здесь". Также, другую ссылку прописью нужно перенести за слово "ссылке".

Пример:
Пожалуйста, подтвердите регистрацию учетной записи перейдя по ссылке http://crm/page/activation/key/c4ef2597d66c75526f5b9e8d или просто нажмите здесь (активная ссылка).

Если так не получится тогда сделаем проще:

Приветствуем, Александр !
Вы зарегистрировались на сайте inclient.ru.
Пожалуйста, подтвердите регистрацию учетной записи перейдя по ссылке (активная ссылка).
Это необходимо для того, чтобы воспользоваться всеми возможностями сайта.
Если в течении 30 дней Вы не подтвердите регистрацию, то Ваш аккаунт будет удален.

С уважением, Администрация INCLIENT.RU

Если у вас возникнут вопросы напишите в поддержку
support@inclient.ru

![2016-02-13_103451](https://cloud.githubusercontent.com/assets/9402056/13026092/7415f8a4-d23d-11e5-8830-1a633f19791a.jpg)

**Comment by Saimonrac1** [comment]
Отмена! все ок. Закрываем - не ошибка.

**Comment by Saimonrac1** [comment]
После того как создал пользователя Создатель компании.
Можем сделать так чтобы предложения начинались с новой строки, а не писались в одну? Вот эти:

Доступ на сайт - http://test.inclient.ru/page/login
Ваш пароль - c877c49e

Если геморрой тогда в долгий ящик. Потом запилим.
![2016-02-18_70](https://cloud.githubusercontent.com/assets/9402056/13153217/ca0ec0dc-d694-11e5-8441-d6c45c73f36c.jpg)

**Comment by Saimonrac1** [comment]
И тут один прикол есть: если мы переходим по ссылке подтвердить аккаунт 2 находясь авторизованным в аккаунте 1, то мы сможем это сделать. Давай пока запилим в этом случае страницу о том что Активация принадлежит другому пользователю. Сделай простую страницу с жирным текстом по центру:

> **Активация принадлежит другому пользователю!**
> Пожалуйста, выйдите из системы и снова перейдите по ссылке из письма. Тогда ваша учетная запись будет активирована.

**Comment by Saimonrac1** [comment]
Не выходит страница "Активация принадлежит другому пользователю!". Сижу под saimonrac@yandex.ru, перешел по ссылке из mail@inclient.ru и смог подтвердить учетку.

![2016-02-19_5](https://cloud.githubusercontent.com/assets/9402056/13174601/a94bbeda-d726-11e5-84b9-b26654426749.jpg)

**Comment by ArseniyDyupin** [comment]
все проверил, все робит, выходит страница с предупреждалкой, все чин по чину
