### ISSUE TITLE
Нет иконок

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#43]
Нет иконок на страницах:

- Клиенты
- Анкета клиента
- Мой аккаунт

![2016-02-13_104037](https://cloud.githubusercontent.com/assets/9402056/13026118/9e534ea4-d23e-11e5-90b2-bcfa3181415e.jpg)
![2016-02-13_104107](https://cloud.githubusercontent.com/assets/9402056/13026120/9f28b530-d23e-11e5-9059-763407e711ed.jpg)
![2016-02-13_104133](https://cloud.githubusercontent.com/assets/9402056/13026119/9f27fd3e-d23e-11e5-85e7-b078697db64c.jpg)

**Comment by ArseniyDyupin** [comment]
хз у меня все есть

**Comment by Saimonrac1** [comment]
Развернул на хостинге - по прежнему нет иконок, проверь еще раз, т.к. они отображаются только у тебя. Проверил на 3 разных браузерах.

**Comment by Saimonrac1** [comment]
нет иконок все равно

![2016-02-16_20](https://cloud.githubusercontent.com/assets/9402056/13084555/a3613a68-d4fb-11e5-99c8-dcdb430a377f.jpg)

**Comment by Saimonrac1** [comment]
Забыли про иконки в окнах Действие по клиенту и Сделка по клиенту

![2016-02-18_59](https://cloud.githubusercontent.com/assets/9402056/13151812/b0d83be0-d68d-11e5-8644-383b08a1bccb.jpg)
![2016-02-18_60](https://cloud.githubusercontent.com/assets/9402056/13151813/b0de1c36-d68d-11e5-95cf-3ebcce9d26f0.jpg)
