### ISSUE TITLE
Добавление клиента: ошибка когда стоит "Нет ответственного"

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#45]
Создаем нового клиента, указываем в параметрах "Нет ответственного", нажимаем кнопку "Добавить клиента" и обана выходит пустая страница, клиент не создается. Тут что то из за параметра "Нет ответственного".

![2016-02-12_212817](https://cloud.githubusercontent.com/assets/9402056/13026145/95015c64-d23f-11e5-879d-1c33c4152aa5.jpg)
![2016-02-12_212732](https://cloud.githubusercontent.com/assets/9402056/13026144/94ffb6ac-d23f-11e5-9db1-5ed3a28432d1.jpg)

**Comment by ArseniyDyupin** [comment]
У админа убираем вариант "Нет ответственного", директору и менеджеру оставляем, при выборе этого варианта, пользователь, действие, сделка, переносятся на админа

**Comment by Saimonrac1** [comment]
Согласовано!

**Comment by ArseniyDyupin** [comment]
1)тут есть еще пара нюансов, таким макаром нет отвествтенного в поиске вообще такой вариант не нужен
2)Может ли манагер(руководитель) видеть все действия в профиле пользователя за которого он ответственный или только те за которые он ответственен и ему надо запретить их редактирование 
короче подумай, потыкайся

**Comment by Saimonrac1** [comment]
Ответы по твоим вопросам:

1) Да, Нет ответственного не нужен у админа, но у руководителей и менеджеров он должен быть. 
2) Руководитель должен видеть все действия и сделки по клиенту если он или его менеджер являются ответственным за этого клиента. В иных случаях руководитель даже попасть не сможет на анкету клиента, если он не ответственный по нему (например, если за действием или сделкой по клиенту ответственный руководитель, но уже за самим клиентом ответственный другой пользователь)

3) Сейчас ошибка наблюдается под руководителем (деректор) и менеджером: если при создании клиента выбираем Нет ответственного, то клиент не создается. Это скорее всего из за нерешенных пунктов 1 и 2, записал чтобы не забыть.

![2016-02-18_49](https://cloud.githubusercontent.com/assets/9402056/13122567/5fe79b18-d5d9-11e5-9d3a-e74f872a0b94.jpg)

**Comment by ArseniyDyupin** [comment]
все 3 пункта нужно обсудить

**Comment by ArseniyDyupin** [comment]
лучше устно, так мы друг друга не поняли

**Comment by ArseniyDyupin** [comment]
1) Из фильтров выпилить вариант нет ответственного
2) В формах создания, редактирования поменять нет ответственного на создатель компании
