### ISSUE TITLE
Дата действия: глюки со временем

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#51]
1. Нужно добавить возможность вколачивать время, сейчас можно назначить только дату. Можно сделать так же как у нас в кабинете (ну ты понял). Также, если возможно то было бы не плохо сразу подставлять время при создании нового действия, например на 30 мин вперед от текущего.
2. После того как создаем действие, заходим на него снова и уже невозможно изменить дату и время через датапикер. Только вручную. 
3. Создаем новое действие, в дате выбираем сегодня. Действие создается с датой действия на текущее время 13.02.16 в 11:23, а в списке действий мы уже можем его найти в просроченных и его дата действия будет 20.02.13 в 16:00. Такого не должно быть. 
4. Также создаем новое действие, назначаем его на 29 февраля, после создания - в анкете клиента оно отображается с датой создания 13.02.16 в 14:17, и в списке действий

После устранения глюков со временем смогу полноценно проверить логику работы действий.

![2016-02-13_1](https://cloud.githubusercontent.com/assets/9402056/13026319/7a82432a-d245-11e5-8d33-53c6c0d5b6b4.jpg)

![2016-02-13_9](https://cloud.githubusercontent.com/assets/9402056/13026940/028691c4-d25d-11e5-8fa8-175ade1019bc.jpg)

![2016-02-13_112528](https://cloud.githubusercontent.com/assets/9402056/13026311/33b9c404-d245-11e5-9c9d-de64f20f31fd.jpg)

**Comment by ArseniyDyupin** [comment]
первый пункт ваще жопа

**Comment by ArseniyDyupin** [comment]
зря сразу не продумал, ща будет дофига работы дополнительной

**Comment by Saimonrac1** [comment]
ок, понял. Делаем, не торопись.

**Comment by ArseniyDyupin** [comment]
В поисках я оставляю обычный датапикер, время просто не влезает

**Comment by Saimonrac1** [comment]
ммм... время нужно обязательно. Без него смысла от действий никакого нет. Какие варианты есть?

**Comment by Saimonrac1** [comment]
закинь скрин как получилось с ним

**Comment by Saimonrac1** [comment]
или отдельное поле для времени сделать

**Comment by ArseniyDyupin** [comment]
отдельное поле говно, лучше поле под полем сделать и все

**Comment by ArseniyDyupin** [comment]
нормальной длинны

**Comment by Saimonrac1** [comment]
У нас проблема с датапикером:
Пример - http://test.inclient.ru/ (под saimonrac@yandex.ru/123456)

1. Действие по клиенту - дату и время в существующем действии можно изменить только вручную
2. Новое действие - в новом действии дата пикер без указания времени
3. Зависает датапикер поконски - у меня вообще под конец тестов просто завис и я с ним ничего сделать не смог, на любой странице сайта.

**Прикол в том что я смог выставить у другого клиента парочку действий без проблем. Помогает очистка кеша полная. Но это не есть хорошо...**

![2016-02-16_24](https://cloud.githubusercontent.com/assets/9402056/13085795/d08cc6b4-d501-11e5-98af-45c69711584e.jpg)
![2016-02-16_25](https://cloud.githubusercontent.com/assets/9402056/13085796/d08fbc2a-d501-11e5-9faf-e12643e7601c.jpg)

**Comment by Saimonrac1** [comment]
нынче поработал, вроде все гуд. Нареканий нет, хороша штука.

**Comment by Saimonrac1** [comment]
В существующем действии нет выбора времени. Оно должно быть. Датапикер не полный. Кеш чистил, проверял в разных браузерах.
