### ISSUE TITLE
Окна по сделке: параметр "Уплачено / Остаток"

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#53]
1. Параметры "Уплачено / Остаток" не должны быть обязательными. Убираем проверку на заполнение.
2. После того как сделка будет добавлена или изменена, то в "Уплачено / Остаток" добавляются лишнии нули, их нужно убрать.

![2016-02-13_5](https://cloud.githubusercontent.com/assets/9402056/13026497/14402afe-d24b-11e5-80de-5c1c665b6970.jpg)
![2016-02-13_6](https://cloud.githubusercontent.com/assets/9402056/13026496/143fccc6-d24b-11e5-8895-bc677db12bb1.jpg)

**Comment by ArseniyDyupin** [comment]
это рубли и копейки, не ну могу убрать, но по мне дк пускай лучше будут

**Comment by Saimonrac1** [comment]
1. Попрежнему "Уплачено / Остаток" надо указывать как обязательные поля. Их не надо вводить обязательно, если значения не заданы можно захерачивать по ним нули.
2. Давай уберем нули. Копейки у нас появятся если что в новом функционале, когда появятся Счета (отдельная история, вкратце: когда мы можем создавать разные счета и управлять ими, расходы, доходы, сделки  и пр. лабуда, пока об этом даже не думай))))

![2016-02-17_44](https://cloud.githubusercontent.com/assets/9402056/13119402/cfdf4c9a-d5ca-11e5-894c-95a2f91461bc.jpg)

**Comment by Saimonrac1** [comment]
Надо сделать так, чтобы в полях был текст Уплачено, Остаток. Сейчас там подставляются нули, и не понятно где уплачено а где остаток. Кроме того, если эти нули стереть то тут же выскакивает предупреждение - такого не должно быть. Короче давай нули уберем, там текст Уплачено и Остаток, когда сделку создаем и данные значения не указаны, то в сделке тогда указываются нули. 

Если так нельзя сделать, тогда в долгий ящик.

![2016-02-22_1](https://cloud.githubusercontent.com/assets/9402056/13211991/52fe5034-d95f-11e5-9c5c-62d6391b7dc4.jpg)
