### ISSUE TITLE
Сделки: ошибка в фильтре Уплачено и Остаток

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#60]
По фильтру "Уплачено: Остаток:" не ищет сумму от и до, т.е. ищет только строго забитую в сделке сумму. Например в сделке остаток 5932, если искать через поиск по остатку то не найти остаток 5000.

Нужно сделать так чтобы по этим параметрам производился поиск суммы до. Пример: в сделке 6666, вбиваю в поиске Остаток 6000 и он выводит мне сделку по которой остаток был 6666.
![2016-02-13_11](https://cloud.githubusercontent.com/assets/9402056/13027431/e38084a0-d271-11e5-9e7e-e639d5a800cf.jpg)

**Comment by Saimonrac1** [comment]
сейчас ищет неправильно, т.е. выводит сделки, у которых остаток меньше, чем вбиваем в поиске. Нужно сделать наоборот немного, т.е.:
- условие поиска - остаток 6000, т.е. показать сделки с остатком до 6000 или равно;
- есть три сделки с остатком 5999,6000 и 60001
- нажимаем Найти и на выходе покажет сделки с остатком 5999 и 6000

Давай это обсудим если необходимо. Когда ставил задачу не полно описал логику, думаю это определение более логично сейчас.
![2016-02-17_42](https://cloud.githubusercontent.com/assets/9402056/13118632/f536fd16-d5c6-11e5-9f38-fbb0bbf28b85.jpg)

**Comment by ArseniyDyupin** [comment]
так и работает Саша

**Comment by ArseniyDyupin** [comment]
как ты описал

**Comment by ArseniyDyupin** [comment]
потести еще раз у тебя одно другому не противоречит а вообще одно и тоже

**Comment by Saimonrac1** [comment]
не, сейчас ищем в поиске остаток до 6666, он показывает сделки с остатком больше или равно 6666. А надо чтобы показывал сделки с остатком меньше или равно 6666.

Короче весь прикол в том чтобы найти сделки с остатком, до или равно суммы остатка обозначенной в поиске. Кстати поиск Уплачено работает как надо. Тут тире наверное сбивает с толку между "Уплачено: - Остаток:", давай его на фиг уберем. 
Давай поясню что почем, если не понял.


![2016-02-18_55](https://cloud.githubusercontent.com/assets/9402056/13150967/c20eed4a-d689-11e5-8721-cf881640d611.jpg)
![2016-02-18_56](https://cloud.githubusercontent.com/assets/9402056/13150968/c2113c80-d689-11e5-96dc-e489bfb9c0d7.jpg)

**Comment by Saimonrac1** [comment]
Давай еще немного подпилим, т.е. надо чтобы при вводе нулей в Уплачено или Остаток, в результате у нас отобразились только сделки с нулевым Уплачено и нулевым Остаток. Сейчас в результате выводятся все сделки, даже у которых уплачено и остаток не нулевые.

![2016-02-20_77](https://cloud.githubusercontent.com/assets/9402056/13195040/570c7b80-d7c8-11e5-90e8-8945a01083ed.jpg)
![2016-02-20_78](https://cloud.githubusercontent.com/assets/9402056/13195041/570e75fc-d7c8-11e5-9d5f-3e7b8c678563.jpg)

**Comment by ArseniyDyupin** [comment]
отображает больше или ровно, мы же это обсуждали в обоих случаях

**Comment by ArseniyDyupin** [comment]
значит все правильно

**Comment by Saimonrac1** [comment]
по нулям так не сделать? ну цель такая - найти нулевые сделки по уплачено или остаток

**Comment by ArseniyDyupin** [comment]
это только на 0 будет так срабатывать? ща запилю

**Comment by ArseniyDyupin** [comment]
ну то есть если вбиваешь 0, что бы выдавал только нулевые, это не логично имхо

**Comment by ArseniyDyupin** [comment]
но сделать без проблем

**Comment by Saimonrac1** [comment]
да, все верно. Только для 0. Например я хочу найти только сделки с нулевым уплачено или нулевым остатком. Сейчас я этого сделать не могу.
