### ISSUE TITLE
Сделки: поиск по Дате создания

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#61]
1. Вбиваю в поиске дату 12.02.2016 (через датапикер) в разделе От, но не вбиваю дату в разделе До - в результате выводятся все сделки, даже те которые были созданы 13 февраля. Тут скорее всего из за того, что нужно обязательно еще вбивать дату в разделе ДО, но нужно сделать так, чтобы результат выводился не вбивая этот раздел (чтобы выводил сделки от даты От до текущего времени). 
2. Тоже самое происходит если вбить дату только в разделе До, но в разделе От мы не указываем дату. Тут нужно так сделать: выводятся сделки начиная от даты создания самой перовой сделки до указанной даты в разделе До.

Если нужно будет пояснить, давай переговорим.
![2016-02-13_12](https://cloud.githubusercontent.com/assets/9402056/13027477/818fa044-d273-11e5-8160-1acb45c18d1b.jpg)

**Comment by ArseniyDyupin** [comment]
Саша - это не логично

**Comment by ArseniyDyupin** [comment]
давай потом обсудим
