### ISSUE TITLE
Анкета клиента: дата действия

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#7]
Ошибка наблюдается как у существующих действий, так и при их создании.

Существующие:

Если в дату выполнения действия  вписать какашку и потом сохранить изменения, то дата выполнения действия не сохранится, будет почему то отображаться дата создания действия.

Новые действия:

Если в дату выполнения ничего не вбиваем, то действие просто не создастся.

Вики:
Окно Действие по клиенту - http://wiki.inclient.ru/index.php/%D0%90%D0%BD%D0%BA%D0%B5%D1%82%D0%B0,_%D0%94%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F_%D0%B8_%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE_%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F
Действия, поиск действий - http://wiki.inclient.ru/index.php/%D0%94%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F,_%D0%BF%D0%BE%D0%B8%D1%81%D0%BA_%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B9

![2015-12-26_122014](https://cloud.githubusercontent.com/assets/9402056/12005530/d64dc6ca-abcb-11e5-8bd1-7ecd6944132c.jpg)

**Comment by Saimonrac1** [comment]
Вопрос: можно ли так сделать, ограничить ввод какашек в поле для даты? Если геморой, тогда забудем об этом пока.

![2016-02-18_48](https://cloud.githubusercontent.com/assets/9402056/13121841/e231d7d6-d5d5-11e5-8b30-e5b172b4a1f5.jpg)

**Comment by ArseniyDyupin** [comment]
гемор, давай отложим
