### ISSUE TITLE
Не изменятеся email создателя компании + нет проверки на сущ. email

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#71]
Не изменяется email админа (Создатель компании) + нет проверки на существующий email. Указываю любой email, нажимаю Изменить, проверки на почту нет, страница обновляется, email не изменяется, письмо с уведомлением не приходит.

![2016-02-16_27](https://cloud.githubusercontent.com/assets/9402056/13086162/c05e529c-d503-11e5-893f-abc4ae92cb0e.jpg)

**Comment by ArseniyDyupin** [comment]
В смысле проверки на уникальный email?

**Comment by Saimonrac1** [comment]
да, а то без проверки можно будет поменять на существующий email. Я просто там не видел проверки
