### ISSUE TITLE
Могу увидеть чужих клиентов

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#76]
У меня всего 4 клиента, id первого начинается с 8 (http://test.inclient.ru/page/client_profile/8)  и  заканчивается последним id 11  (http://test.inclient.ru/page/client_profile/11). Стоит мне поменять в последнюю цифру в ссылке своего клиента, как я смогу перейти на клиента от другой компании. 
Такого не должно быть.

Можно сделать, чтобы id пользователей были обозначены только для одной компании? А также, чтобы доступы к ним были ограничены как то, чтобы пользователи не видели чужих клиентов?
Это серьезный вопрос, если будут какие либо предложения для обсуждения говори. Надо сделать так, чтобы люди никоим образом не видели клиентов за которыми они не ответственны.

Может типо как в гитхабе - https://github.com/ArseniyDyupin/SimpleCRM2/issues/new, видишь они вставляют уникальный определитель "ArseniyDyupin". Или это сложно? Может при создании компании заставлять указывать какой то свой уникальный домен или логин?

![2016-02-17_31](https://cloud.githubusercontent.com/assets/9402056/13087586/7f8f3162-d50a-11e5-9b6e-ba95136d829f.jpg)

**Comment by ArseniyDyupin** [comment]
ты не поверишь, она у меня в блокноте была записана))

**Comment by ArseniyDyupin** [comment]
ну эта задача всмычле

**Comment by saimonrac** [comment]
ок!

**Comment by ArseniyDyupin** [comment]
еще заблочил для всяких не ответственных за клиента ну и по компаниям само собой
