### ISSUE TITLE
404 ошибку сделать

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#79]
Вводим казядабру в адресную строку и получаем кусок кода. Надо нацепить для таких дел 404 ошибку. Я ее подготовлю и захерачим.

Задача пока на мне. Я подготовлю верстку.

**Comment by ArseniyDyupin** [comment]
логику исправил, жду нормальную верстку 404 страницы

**Comment by Saimonrac1** [comment]
404 ошибку запилил и закомитил
