### ISSUE TITLE
Удаление пользователя - надо логику доработать

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#83]
У нас сейчас беда происходит если удаляем пользователя (менеджера или директора): удаляются все их клиенты, действия и сделки.

Давай с тобой согласуем этот момент. Предлагаю следующее.

**При удалении менеджера:**
- если он прикреплен к руководителю - всех клиентов, действия и сделки, по которым менеджер был ответственным, закреплять после удаления за его руководителем;
- если он ни за кем не закреплен (т.е. закреплен за админом) - всех клиентов, действия и сделки, по которым менеджер был ответственным, закреплять после удаления за админом.

**При удалении руководителя:**
-  всех клиентов, действия и сделки, по которым руководитель был ответственным, закреплять после удаления за админом. Менеджеров, которые были закреплены за этим руководителем, прикреплять к админу.

Сразу тоже не подумал над этой кутерьмой. Давай согласуем, если подходит делаем, если нет давай подумаем или доработаем.

Связанная задача - https://github.com/ArseniyDyupin/SimpleCRM2/issues/85

**Comment by ArseniyDyupin** [comment]
да не, че тут мудрить то, все логично написал, так и сделаем
