### ISSUE TITLE
Ошибка PHP если авторизован под удаленнмы пользователем

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#86]
Был авторизован менедежером, под админом удалили этого менеджера, обновил странице под менеджером - вышла ошибка PHP. Тут надо выводить какую нибудь 404 ошибку.

![2016-02-18_51](https://cloud.githubusercontent.com/assets/9402056/13149605/ddec74de-d683-11e5-984a-45674775740c.jpg)

**Comment by ArseniyDyupin** [comment]
сделал вывод окна авторизации вместо 404 ошибкой, по-моему так логичней и симпотичней

**Comment by Saimonrac1** [comment]
Все гуд! Отлично!
