### ISSUE TITLE
Время создания клиента и сделки от хостинга

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#96]
Клиенты и сделки создаются по времени хостинга, тогда как надо чтобы они создавались по времени локального ПК. При создании действий например такого не наблюдается, там все гуд.

![2016-02-19_12](https://cloud.githubusercontent.com/assets/9402056/13176210/2058567c-d732-11e5-8931-674d22d15e70.jpg)
![2016-02-19_13](https://cloud.githubusercontent.com/assets/9402056/13176211/2058bb9e-d732-11e5-9382-26fd4579c2f0.jpg)

**Comment by ArseniyDyupin** [comment]
Добавить настройку часового пояса в профиль пользователя

**Comment by Saimonrac1** [comment]
Убираем в следующий релиз. Пока в долгий ящик эту задачу
