### ISSUE TITLE
Не находит сделку за период в поиске

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#97]
За 19 февраля ищу 3 сделки за период с 0:00 по 14:22, по результату выводится только две сделки, хотя по факту сделки три за это время, т.е. в 14:00, в 14:20, в 14:22. Сделку в в 14:22 не отобразил почему то.

![2016-02-20_75](https://cloud.githubusercontent.com/assets/9402056/13195001/76cf8e86-d7c7-11e5-9855-5fa95780afd6.jpg)
![2016-02-20_76](https://cloud.githubusercontent.com/assets/9402056/13195000/76ce2258-d7c7-11e5-8c48-4288716d01c0.jpg)

**Comment by ArseniyDyupin** [comment]
тут дело в секундах

**Comment by Saimonrac1** [comment]
Можем вообще убрать такие секунды? или ты уже их убрал?
