### ISSUE TITLE
Глюк со справкой

### ISSUE THREAD

**Issue by Saimonrac1** [ArseniyDyupin/SimpleCRM2#98]
Открываем окно существующего действия, закрываем его, открываем окно Новое действие, жмем  на "Показать справку" и блок не раскрывается. Он скачет туда сюда, но развернуться не может. Помогает только очистка кеша, но потом снова повторяется.

**Тоже самое происходит со сделками (окно Новая сделка) и пользователями (окно Новый пользователь, здесь даже информ. блок пропадает).**

![2016-02-22_2](https://cloud.githubusercontent.com/assets/9402056/13214504/d31baa48-d971-11e5-80ae-c8463fc0f5dc.jpg)
![2016-02-22_3](https://cloud.githubusercontent.com/assets/9402056/13214505/d3469dfc-d971-11e5-872f-168a85f4ec1c.jpg)
![2016-02-22_4](https://cloud.githubusercontent.com/assets/9402056/13214506/d35d96b0-d971-11e5-8bbb-a08f7064dc10.jpg)

**Comment by ArseniyDyupin** [comment]
это косяк верстака, но я подумаю как исправить

**Comment by Saimonrac1** [comment]
ок, спасибо
